'use client';

import React, { useState } from 'react';
import { Database, ClueType, ImplicationType, EvidenceStatus } from '@/types/database';
import { updateClueAction } from '../actions';
import { generateCluePreview, suggestCluePrompts, generateClueDescriptionAction, generateClueImageAction } from '@/app/actions/generator';
import { hydrateTextWithCharacters } from '@/utils/hydration';

type Clue = Database['public']['Tables']['clues']['Row'];
type Beat = Database['public']['Tables']['plot_beats']['Row'];
type Character = Database['public']['Tables']['characters']['Row'];

interface ClueEditorProps {
  clue: Clue;
  mysteryId: string;
  beats: Beat[];
  characters: Character[];
  subplots?: any[];
  onClose: () => void;
}

export function ClueEditor({ clue, mysteryId, beats, characters, subplots = [], onClose }: ClueEditorProps) {
  const [isSaving, setIsSaving] = useState(false);
  const [title, setTitle] = useState(clue.title || '');
  const [description, setDescription] = useState(clue.description || '');
  const [generationPrompt, setGenerationPrompt] = useState(clue.generation_prompt || '');
  const [templateText, setTemplateText] = useState(clue.template_text || '');
  
  const [isGeneratingPreview, setIsGeneratingPreview] = useState(false);
  const [isGeneratingDescription, setIsGeneratingDescription] = useState(false);
  const [isSuggesting, setIsSuggesting] = useState(false);
  const [suggestions, setSuggestions] = useState<string[]>([]);

  const [imageUrl, setImageUrl] = useState<string | null>(clue.static_image_url || null);
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  const [imageError, setImageError] = useState<string | null>(null);
  
  const [focusedInput, setFocusedInput] = useState<'description' | 'generation_prompt'>('description');
  const [showDetails, setShowDetails] = useState(false);

  const defaultLinkedBeat = clue.evidence_status === 'fake' || (!clue.linked_plot_beat_id && !clue.linked_subplot_beat_id)
    ? 'fake'
    : clue.linked_plot_beat_id
    ? `main_${clue.linked_plot_beat_id}`
    : `sub_${clue.linked_subplot_beat_id}`;

  const [linkedBeatValue, setLinkedBeatValue] = useState(defaultLinkedBeat);

  const handleSuggestPrompts = async () => {
    setIsSuggesting(true);
    try {
      let activeBeatTitle = 'A Mysterious Event';
      if (linkedBeatValue && linkedBeatValue.startsWith('main_')) {
        const beatId = linkedBeatValue.replace('main_', '');
        const beat = beats.find(b => b.id === beatId);
        if (beat) activeBeatTitle = beat.event_title;
      } else if (linkedBeatValue && linkedBeatValue.startsWith('sub_')) {
        const beatId = linkedBeatValue.replace('sub_', '');
        const beat = subplots?.flatMap(s => s.subplot_beats || []).find((b: any) => b.id === beatId);
        if (beat) activeBeatTitle = beat.description;
      } else if (linkedBeatValue === 'fake') {
        activeBeatTitle = 'Fake Clue / Unlinked to Story Timeline';
      }

      const results = await suggestCluePrompts(activeBeatTitle);
      setSuggestions(results);
    } catch (e: any) {
      console.error('Action Error:', e);
      alert('Failed to fetch suggestions: ' + (e?.message || String(e)));
    }
    setIsSuggesting(false);
  };

  const handleAutogenerateDescription = async () => {
    if (!title.trim()) {
      alert('Please enter an Evidence Name before generating a description.');
      return;
    }
    setIsGeneratingDescription(true);
    try {
      let activeBeatTitle = 'A Mysterious Event';
      if (linkedBeatValue && linkedBeatValue.startsWith('main_')) {
        const beatId = linkedBeatValue.replace('main_', '');
        const beat = beats.find(b => b.id === beatId);
        if (beat) activeBeatTitle = beat.event_title;
      } else if (linkedBeatValue && linkedBeatValue.startsWith('sub_')) {
        const beatId = linkedBeatValue.replace('sub_', '');
        const beat = subplots?.flatMap(s => s.subplot_beats || []).find((b: any) => b.id === beatId);
        if (beat) activeBeatTitle = beat.description;
      } else if (linkedBeatValue === 'fake') {
        activeBeatTitle = 'Fake Clue / Unlinked to Story Timeline';
      }

      // Hydrate characters in prompt so the generated text has correct genders & attributes
      const hydratedPrompt = hydrateTextWithCharacters(generationPrompt, characters, 'ai');

      const result = await generateClueDescriptionAction(title, activeBeatTitle, hydratedPrompt);
      setDescription(result);
    } catch (e: any) {
      console.error('Description Gen Error:', e);
      alert('Failed to autogenerate description: ' + (e?.message || String(e)));
    }
    setIsGeneratingDescription(false);
  };

  const handleTestPrompt = async () => {
    setIsGeneratingPreview(true);
    try {
      const hydratedPrompt = hydrateTextWithCharacters(generationPrompt, characters, 'ai');
      const result = await generateCluePreview(hydratedPrompt, templateText);
      setTemplateText(result);
      if (!description) {
        setDescription(result);
      }
    } catch (e: any) {
      console.error('Preview Error:', e);
      alert('Failed to generate preview. Server said: ' + (e?.message || String(e)));
    }
    setIsGeneratingPreview(false);
  };

  const handleGenerateImage = async () => {
    if (!generationPrompt.trim()) {
      alert('Please enter an AI Image Description / Generation Prompt first.');
      return;
    }
    setIsGeneratingImage(true);
    setImageError(null);
    try {
      const res = await generateClueImageAction(clue.id, mysteryId, generationPrompt);
      if (res?.success && res.imageUrl) {
        setImageUrl(res.imageUrl);
      } else if (res?.error) {
        setImageError(res.error);
      }
    } catch (e: any) {
      console.error('Image Generation Error:', e);
      setImageError(e.message || 'An error occurred during image generation.');
    } finally {
      setIsGeneratingImage(false);
    }
  };

  const handleInsertTag = (tag: string) => {
    const inputId = focusedInput === 'description' ? 'clue-description' : 'clue-generation-prompt';
    const textarea = document.getElementById(inputId) as HTMLTextAreaElement;
    if (!textarea) return;

    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const text = textarea.value;
    const before = text.substring(0, start);
    const after = text.substring(end, text.length);
    const newText = before + tag + after;

    if (focusedInput === 'description') {
      setDescription(newText);
    } else {
      setGenerationPrompt(newText);
    }

    setTimeout(() => {
      textarea.focus();
      textarea.selectionStart = textarea.selectionEnd = start + tag.length;
    }, 50);
  };

  const clueTypes: ClueType[] = ['physical', 'testimony', 'background', 'secret'];
  const implications: ImplicationType[] = ['direct', 'circumstantial', 'red_herring'];

  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm animate-in fade-in duration-300" 
        onClick={onClose}
      />
      
      {/* Panel */}
      <div className="relative w-full max-w-xl bg-white h-full shadow-2xl animate-in slide-in-from-right duration-500 overflow-y-auto custom-scrollbar flex flex-col">
        <div className="p-10 flex-grow">
          <div className="flex justify-between items-center mb-10">
            <h2 className="text-2xl font-black text-slate-900">Evidence File</h2>
            <button 
              onClick={onClose}
              className="w-10 h-10 rounded-full bg-slate-50 flex items-center justify-center text-slate-400 hover:text-slate-900 transition-colors"
            >
              ✕
            </button>
          </div>

          <form 
            action={async (formData) => {
              setIsSaving(true);
              const beatSelection = formData.get('linked_beat') as string;
              let linked_plot_beat_id = null;
              let linked_subplot_beat_id = null;
              let evidence_status: EvidenceStatus = (formData.get('evidence_status') as EvidenceStatus) || 'real';

              if (beatSelection && beatSelection.startsWith('main_')) {
                linked_plot_beat_id = beatSelection.replace('main_', '');
                if (evidence_status === 'fake') evidence_status = 'real';
              } else if (beatSelection && beatSelection.startsWith('sub_')) {
                linked_subplot_beat_id = beatSelection.replace('sub_', '');
                if (evidence_status === 'fake') evidence_status = 'real';
              } else if (beatSelection === 'fake') {
                evidence_status = 'fake';
              }

              const updates = {
                title,
                description,
                generation_prompt: generationPrompt,
                template_text: templateText,
                linked_plot_beat_id,
                linked_subplot_beat_id,
                evidence_status,
                clue_type: (formData.get('clue_type') as ClueType) || clue.clue_type,
                implication_type: (formData.get('implication_type') as ImplicationType) || clue.implication_type,
                is_essential: formData.get('is_essential') === 'on',
                internal_notes: formData.get('internal_notes') as string,
                asset_mode: (formData.get('asset_mode') as any) || clue.asset_mode,
              };

              await updateClueAction(mysteryId, clue.id, updates);
              setIsSaving(false);
              onClose();
            }}
            className="space-y-8"
          >
            {/* 1. Name */}
            <div>
              <label className="block text-xs font-bold text-slate-500 mb-2">Evidence Name</label>
              <input 
                name="title"
                value={title}
                onChange={e => setTitle(e.target.value)}
                required
                className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl font-bold outline-none focus:ring-2 focus:ring-brand-blue/20"
                placeholder="e.g. Broken Wine Glass, Crumpled Receipt..."
              />
            </div>

            {/* 2. Reveal Point (Timeline Beat) */}
            <div>
              <label className="block text-xs font-bold text-slate-500 mb-2">Reveal Point (Timeline Beat)</label>
              <select 
                name="linked_beat" 
                value={linkedBeatValue}
                onChange={e => setLinkedBeatValue(e.target.value)}
                className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl font-bold text-xs appearance-none outline-none focus:ring-2 focus:ring-brand-blue/20"
              >
                <option value="fake">🚫 Fake Clue (Not linked to timeline)</option>
                <optgroup label="Main Timeline Beats">
                  {beats.map(b => (
                    <option key={`main_${b.id}`} value={`main_${b.id}`}>
                      Beat {b.beat_number}: {b.event_title}
                    </option>
                  ))}
                </optgroup>
                {subplots.map(subplot => (
                  <optgroup key={`subgroup_${subplot.id}`} label={`Subplot: ${subplot.title}`}>
                    {subplot.subplot_beats?.map((sb: any) => (
                      <option key={`sub_${sb.id}`} value={`sub_${sb.id}`}>
                        Beat {sb.beat_number}: {sb.description}
                      </option>
                    ))}
                  </optgroup>
                ))}
              </select>
            </div>

            {/* 3. Internal Description */}
            <div>
              <div className="flex justify-between items-end mb-2">
                <label className="block text-xs font-bold text-slate-500">Internal Description (Printed Card Text)</label>
                <button
                  type="button"
                  onClick={handleAutogenerateDescription}
                  disabled={isGeneratingDescription}
                  className="text-[10px] font-bold text-brand-pink hover:text-brand-pink/80 flex items-center gap-1 disabled:opacity-50"
                >
                  {isGeneratingDescription ? 'Writing...' : '✨ Autogenerate Card Text'}
                </button>
              </div>
              <textarea 
                id="clue-description"
                name="description"
                value={description}
                onChange={e => setDescription(e.target.value)}
                onFocus={() => setFocusedInput('description')}
                rows={4}
                placeholder="Write the public description players will read on the printed card..."
                className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl font-bold outline-none focus:ring-2 focus:ring-brand-blue/20 resize-none"
              />
            </div>

            {/* Dynamic Character Mention Tags */}
            <div className="p-4 bg-slate-50/60 rounded-2xl border border-slate-100">
               <p className="text-[10px] font-bold text-slate-400 mb-2.5 uppercase tracking-widest flex items-center gap-1.5">
                 👤 Mention Characters ({characters.length})
               </p>
               <div className="flex flex-wrap gap-2">
                 {characters.map(char => {
                   const cleanName = char.name.split('|')[0]?.trim() || char.name;
                   const tag = `{{${cleanName}}}`;
                   return (
                     <button
                       key={char.id}
                       type="button"
                       onClick={() => handleInsertTag(tag)}
                       className="px-2.5 py-1.5 bg-white border border-slate-200 rounded-xl text-[10px] font-bold text-slate-700 hover:text-brand-pink hover:border-brand-pink hover:bg-brand-pink/5 transition-all shadow-sm flex items-center gap-1 active:scale-95 cursor-pointer"
                     >
                       {tag}
                     </button>
                   );
                 })}
               </div>
               <p className="text-[9px] text-slate-400 mt-2 font-medium italic leading-relaxed">
                 Click a character name to insert at current cursor. Substitutions occur automatically at runtime (Guest names on prints, guest appearances in prompts).
               </p>
            </div>

            {/* 4. AI Image Description */}
            <div className="space-y-6 bg-brand-pink/5 p-8 rounded-[2rem] border border-brand-pink/10">
              <div className="flex justify-between items-center border-b border-brand-pink/10 pb-4">
                <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-brand-pink">AI Image Description</h3>
                <select 
                  name="asset_mode" 
                  defaultValue={clue.asset_mode || 'static'} 
                  className="px-3 py-1 bg-white border border-brand-pink/20 rounded-lg text-[10px] font-black uppercase tracking-widest outline-none"
                >
                  <option value="static">Manual Mode</option>
                  <option value="generated">AI Prompt Mode</option>
                </select>
              </div>

              <div className="space-y-4">
                <div>
                  <div className="flex justify-between items-end mb-2">
                    <label className="block text-xs font-bold text-brand-pink/60">Generation Prompt</label>
                    <button
                      type="button"
                      onClick={handleSuggestPrompts}
                      disabled={isSuggesting}
                      className="text-[10px] font-bold text-brand-pink hover:text-brand-pink/80 flex items-center gap-1 disabled:opacity-50"
                    >
                      {isSuggesting ? 'Thinking...' : '✨ Suggest Visual Ideas'}
                    </button>
                  </div>

                  {suggestions.length > 0 && (
                    <div className="mb-4 space-y-2">
                      {suggestions.map((suggestion, idx) => (
                        <button
                          key={idx}
                          type="button"
                          onClick={() => setGenerationPrompt(suggestion)}
                          className="w-full text-left p-3 rounded-xl bg-white border border-brand-pink/20 hover:border-brand-pink hover:bg-brand-pink/5 transition-all group"
                        >
                          <span className="text-xs text-slate-600 font-medium group-hover:text-slate-900 leading-snug block">{suggestion}</span>
                          <span className="text-[9px] font-bold text-brand-pink mt-1 block uppercase tracking-widest">Use This Idea</span>
                        </button>
                      ))}
                    </div>
                  )}

                  <textarea 
                    id="clue-generation-prompt"
                    name="generation_prompt"
                    value={generationPrompt}
                    onChange={e => setGenerationPrompt(e.target.value)}
                    onFocus={() => setFocusedInput('generation_prompt')}
                    rows={4}
                    placeholder="Specific details for the illustration (e.g. {{Dane}}'s muddy fingerprint on a champagne bottle)..."
                    className="w-full px-6 py-4 bg-white border border-brand-pink/10 rounded-2xl font-bold text-xs outline-none focus:ring-2 focus:ring-brand-pink/20 resize-none"
                  />
                  
                  <div className="mt-4 flex flex-col sm:flex-row justify-between items-stretch sm:items-center gap-3">
                    <p className="text-[10px] text-slate-400 font-medium italic max-w-xs leading-relaxed">
                      Describes the visual settings and key details. Characters mentioned will match real guests.
                    </p>
                    <div className="flex gap-2 justify-end">
                      <button
                        type="button"
                        onClick={handleTestPrompt}
                        disabled={isGeneratingPreview || !generationPrompt}
                        className="px-4 py-2 bg-white border border-brand-pink/20 text-brand-pink hover:bg-brand-pink/5 rounded-xl text-xs font-bold transition-all disabled:opacity-50"
                      >
                        {isGeneratingPreview ? 'Writing...' : 'Preview Text'}
                      </button>
                      <button
                        type="button"
                        onClick={handleGenerateImage}
                        disabled={isGeneratingImage || !generationPrompt}
                        className="px-5 py-2 bg-brand-pink text-white rounded-xl text-xs font-bold hover:bg-brand-pink/80 transition-all shadow-lg shadow-brand-pink/20 disabled:opacity-50 flex items-center gap-1.5"
                      >
                        {isGeneratingImage ? (
                          <>
                            <svg className="animate-spin h-3.5 w-3.5" viewBox="0 0 24 24" fill="none">
                              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                            Drawing...
                          </>
                        ) : (
                          <>
                            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L28 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                            </svg>
                            Generate Photo
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                </div>

                {/* Photo Preview Card */}
                <div className="space-y-2 mt-4">
                  <label className="block text-xs font-bold text-brand-pink/60">Clue Photo Illustration Preview</label>
                  <div className="w-full aspect-square bg-white border border-brand-pink/15 rounded-3xl overflow-hidden relative group shadow-inner flex flex-col items-center justify-center transition-all duration-300">
                    {imageUrl ? (
                      <div className="absolute inset-0 w-full h-full">
                        <img
                          src={imageUrl}
                          alt="Clue Photo Preview"
                          className="w-full h-full object-cover grayscale-[20%] sepia-[10%] contrast-[1.05] brightness-[0.95] group-hover:grayscale-0 group-hover:sepia-0 group-hover:brightness-100 transition-all duration-700"
                        />
                        {/* Hover Overlay */}
                        <div className="absolute inset-0 bg-slate-900/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center gap-3">
                          <button
                            type="button"
                            onClick={handleGenerateImage}
                            disabled={isGeneratingImage}
                            className="px-4 py-2 bg-white/95 text-slate-900 text-[11px] font-black uppercase tracking-wider rounded-xl hover:bg-brand-pink hover:text-white transition-all shadow-md active:scale-95 disabled:opacity-50"
                          >
                            ⚡ Regenerate Illustration
                          </button>
                        </div>
                      </div>
                    ) : (
                      <div className="p-8 text-center flex flex-col items-center justify-center space-y-4">
                        <div className="w-16 h-16 rounded-2xl bg-brand-pink/5 flex items-center justify-center text-brand-pink/30 group-hover:scale-110 transition-transform duration-500">
                          <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" />
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
                          </svg>
                        </div>
                        <div>
                          <p className="text-[11px] font-black uppercase tracking-wider text-slate-500">No Photo Generated</p>
                          <p className="text-[10px] text-slate-400 font-medium mt-1 leading-normal max-w-[220px] mx-auto">
                            Illustrate this clue with a premium Gemini-generated photo.
                          </p>
                        </div>
                        <button
                          type="button"
                          onClick={handleGenerateImage}
                          disabled={isGeneratingImage || !generationPrompt}
                          className="px-4 py-2 bg-brand-pink/10 hover:bg-brand-pink text-brand-pink hover:text-white border border-brand-pink/20 rounded-xl text-[11px] font-bold transition-all disabled:opacity-50"
                        >
                          Generate Photo Preview
                        </button>
                      </div>
                    )}

                    {/* Loading Overlay */}
                    {isGeneratingImage && (
                      <div className="absolute inset-0 bg-slate-900/70 backdrop-blur-sm flex flex-col items-center justify-center text-white space-y-4 animate-in fade-in duration-300">
                        <div className="relative flex items-center justify-center">
                          <div className="w-12 h-12 rounded-full border-4 border-brand-pink/20 border-t-brand-pink animate-spin"></div>
                          <svg className="w-5 h-5 text-brand-pink absolute animate-pulse" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
                          </svg>
                        </div>
                        <div className="text-center">
                          <p className="text-xs font-black uppercase tracking-widest text-brand-pink animate-pulse">Gemini Imagen 4.0</p>
                          <p className="text-[10px] text-slate-300 font-bold mt-1">Fleshing out visual mystery details...</p>
                        </div>
                      </div>
                    )}

                    {/* Error Overlay */}
                    {imageError && (
                      <div className="absolute inset-0 bg-red-950/90 p-6 flex flex-col items-center justify-center text-center space-y-3 animate-in fade-in">
                        <div className="w-10 h-10 rounded-full bg-red-500/20 flex items-center justify-center text-red-400">
                          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                          </svg>
                        </div>
                        <div>
                          <p className="text-xs font-black uppercase tracking-widest text-red-400">Generation Error</p>
                          <p className="text-[10px] text-red-200 mt-1 max-w-[220px] leading-relaxed mx-auto font-medium">{imageError}</p>
                        </div>
                        <button
                          type="button"
                          onClick={() => setImageError(null)}
                          className="px-3 py-1 bg-red-500 hover:bg-red-600 text-white rounded-lg text-[10px] font-bold transition-all"
                        >
                          Try Again
                        </button>
                      </div>
                    )}
                  </div>
                </div>

                {templateText && (
                  <div>
                    <label className="block text-xs font-bold text-brand-pink/60 mb-2">Clue Document / AI Text Preview</label>
                    <textarea 
                      name="template_text"
                      value={templateText}
                      onChange={e => setTemplateText(e.target.value)}
                      rows={4}
                      placeholder="Raw text to overlay in previews..."
                      className="w-full px-6 py-4 bg-white border border-brand-pink/10 rounded-2xl font-bold text-xs outline-none focus:ring-2 focus:ring-brand-pink/20 resize-none"
                    />
                  </div>
                )}
              </div>
            </div>

            {/* Collapsible Details Section */}
            <div className="border-t border-slate-100 pt-6">
              <button
                type="button"
                onClick={() => setShowDetails(!showDetails)}
                className="w-full flex items-center justify-between py-2 text-xs font-black uppercase tracking-widest text-slate-400 hover:text-slate-600 transition-colors"
              >
                <span>⚙️ Additional Classification Details</span>
                <span>{showDetails ? '▲ Hide' : '▼ Show'}</span>
              </button>

              {showDetails && (
                <div className="space-y-6 pt-6 animate-in fade-in slide-in-from-top-2 duration-300">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-xs font-bold text-slate-500 mb-2">Clue Type</label>
                      <select 
                        name="clue_type" 
                        defaultValue={clue.clue_type || 'physical'} 
                        className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl font-bold text-xs appearance-none"
                      >
                        {clueTypes.map(t => <option key={t} value={t}>{t.charAt(0).toUpperCase() + t.slice(1)}</option>)}
                      </select>
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-slate-500 mb-2">Implication</label>
                      <select 
                        name="implication_type" 
                        defaultValue={clue.implication_type || 'circumstantial'} 
                        className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl font-bold text-xs appearance-none"
                      >
                        {implications.map(i => <option key={i} value={i}>{i.replace('_', ' ').toUpperCase()}</option>)}
                      </select>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-4 p-4 bg-slate-50 rounded-2xl">
                     <input 
                       type="checkbox" 
                       name="is_essential" 
                       defaultChecked={clue.is_essential}
                       className="w-6 h-6 rounded-lg accent-brand-blue"
                     />
                     <div>
                        <span className="block text-xs font-bold text-slate-900">Essential Evidence</span>
                        <span className="text-[10px] text-slate-400 font-medium italic">Is this required to solve the case?</span>
                     </div>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-500 mb-2">Designer Notes</label>
                    <textarea 
                      name="internal_notes"
                      defaultValue={clue.internal_notes || ''}
                      rows={3}
                      placeholder="Internal clues, logic trails, or hidden details..."
                      className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl font-medium text-xs outline-none focus:ring-2 focus:ring-brand-blue/20 resize-none italic"
                    />
                  </div>
                </div>
              )}
            </div>

            <div className="pt-6 flex gap-4">
               <button 
                 type="button" 
                 onClick={onClose}
                 className="flex-grow py-4 bg-slate-50 text-slate-500 rounded-2xl font-bold hover:bg-slate-100 transition-all"
               >
                 Cancel
               </button>
               <button 
                 type="submit"
                 disabled={isSaving}
                 className="flex-grow py-4 bg-slate-900 text-white rounded-2xl font-bold hover:bg-brand-blue transition-all shadow-xl shadow-slate-900/10 disabled:opacity-50 animate-in fade-in"
               >
                 {isSaving ? 'Updating...' : 'Save Evidence'}
               </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
